# Generated by Django 2.2.6 on 2019-10-22 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_article_on_like_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='on_like_users',
            new_name='liked_users',
        ),
    ]
